const STREAM_URL = "https://radio.megahostec.com/listen/eden/stream";
const NOW_PLAYING_URLS = ["https://radio.megahostec.com/api/nowplaying/eden","https://radio.megahostec.com/api/nowplaying/1"];
const $ = id => document.getElementById(id);
const radio=$("radio"), playBtn=$("playBtn"), statusEl=$("status"), songTitle=$("songTitle"), artistName=$("artistName"), albumArt=$("albumArt"), menu=$("menu"), overlay=$("overlay");
let deferredPrompt;
const lang=(navigator.language||"es").toLowerCase().startsWith("en")?"en":"es";
const t={es:{tagline:"La fe viene por el oír",home:"Inicio",word:"Palabra",pastVerses:"Versículos pasados",donations:"Donaciones",shop:"Tienda",social:"Redes",shareApp:"Compartir app",live:"EN VIVO",install:"Instalar",tapPlay:"Toca play para escuchar",wordToday:"📖 Palabra para hoy",verseOfDay:"Versículo del día",seePast:"Ver versículos pasados",library:"📚 Biblioteca",donationsText:"Pronto podrás apoyar este ministerio. Puedes conectar Cash App, PayPal, Zelle o Stripe cuando tengas la cuenta lista.",shopText:"Espacio reservado para camisetas, gorras y productos de Edén. Luego se puede conectar con Shopify, Square, PayPal o enlaces directos.",soon:"Próximamente",share:"Compartir",paused:"PAUSADO",connecting:"Conectando...",onair:"EN VIVO",secondTap:"iPhone puede pedir una segunda pulsación para iniciar el audio.",unavailable:"Señal no disponible"},en:{tagline:"Faith comes by hearing",home:"Home",word:"Word",pastVerses:"Past verses",donations:"Donations",shop:"Shop",social:"Social",shareApp:"Share app",live:"LIVE",install:"Install",tapPlay:"Tap play to listen",wordToday:"📖 Word for today",verseOfDay:"Verse of the day",seePast:"See past verses",library:"📚 Library",donationsText:"Soon you will be able to support this ministry. You can connect Cash App, PayPal, Zelle or Stripe when the account is ready.",shopText:"Reserved for Edén shirts, hats and products. Later it can connect to Shopify, Square, PayPal or direct links.",soon:"Coming soon",share:"Share",paused:"PAUSED",connecting:"Connecting...",onair:"LIVE",secondTap:"iPhone may ask you to tap play one more time to start audio.",unavailable:"Signal unavailable"}}[lang];
document.documentElement.lang=lang; document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(t[k]) el.textContent=t[k]});
window.addEventListener("load",()=>setTimeout(()=>$("splash")?.classList.add("hide"),800));
function setStatus(text){statusEl.textContent=text} function setPlayingUI(isPlaying){playBtn.classList.toggle("playing",isPlaying);playBtn.querySelector("span").textContent=isPlaying?"❚❚":"▶"}
playBtn.addEventListener("click",async()=>{try{if(!radio.src){radio.src=STREAM_URL+"?t="+Date.now();radio.load()} if(radio.paused){setStatus(t.connecting);await radio.play();setPlayingUI(true);setStatus(t.onair)}else{radio.pause();setPlayingUI(false);setStatus(t.paused)}}catch(err){setPlayingUI(false);setStatus(t.tapPlay);songTitle.textContent=t.secondTap}});
radio.addEventListener("playing",()=>{setPlayingUI(true);setStatus(t.onair)}); radio.addEventListener("pause",()=>{setPlayingUI(false);setStatus(t.paused)}); radio.addEventListener("waiting",()=>setStatus(t.connecting)); radio.addEventListener("error",()=>{setPlayingUI(false);setStatus(t.unavailable)});
function cleanMeta(artist,title){artist=(artist||"").trim(); title=(title||"").trim(); if(title.includes(" - ") && (!artist || artist.toLowerCase().includes("now on air"))){const parts=title.split(" - "); artist=parts.shift().replace(/now on air:?/i,"").trim(); title=parts.join(" - ").trim()} artist=artist.replace(/^now on air:*/i,"").trim(); title=title.replace(/^now on air:*/i,"").trim(); return {artist: artist||"Edén", title: title||"Música cristiana 24/7"};}
async function updateNowPlaying(){for(const url of NOW_PLAYING_URLS){try{const res=await fetch(url,{cache:"no-store"}); if(!res.ok) continue; const data=await res.json(); const np=data.now_playing||data; const song=np.song||{}; const meta=cleanMeta(song.artist||np.artist, song.title||np.title||np.text); artistName.textContent=meta.artist; songTitle.textContent=meta.title; const art=song.art||song.custom_fields?.art||np.art; if(art && !/megahostec|azuracast|default/i.test(art)){albumArt.innerHTML=`<img src="${art}" alt="Album art">`}else{albumArt.innerHTML='<img src="assets/logo.png" alt="Edén">'} return}catch(e){}} artistName.textContent="Edén"; songTitle.textContent="Música cristiana 24/7"; albumArt.innerHTML='<img src="assets/logo.png" alt="Edén">'}
updateNowPlaying(); setInterval(updateNowPlaying,30000);
const verses=[
 {date:"Mar 9 2026",ref:"Marcos 12:30",text:"Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente y con todas tus fuerzas.",reflection:"Que todo lo que hagas hoy nazca del amor a Dios."},
 {date:"Mar 10 2026",ref:"Romanos 10:17",text:"La fe viene por el oír, y el oír, por la palabra de Dios.",reflection:"Deja que la Palabra levante tu ánimo y dirija tu día."},
 {date:"Mar 11 2026",ref:"Mateo 6:33",text:"Mas buscad primeramente el reino de Dios y su justicia.",reflection:"Pon a Dios primero; lo demás encuentra su lugar."},
 {date:"Mar 12 2026",ref:"Filipenses 4:13",text:"Todo lo puedo en Cristo que me fortalece.",reflection:"Tu fuerza no nace del cansancio, nace de Cristo."},
 {date:"Mar 13 2026",ref:"Salmos 23:1",text:"Jehová es mi pastor; nada me faltará.",reflection:"Dios sabe cuidar lo que tú no puedes controlar."},
 {date:"Mar 14 2026",ref:"Josué 1:9",text:"Mira que te mando que te esfuerces y seas valiente.",reflection:"Avanza con fe. No caminas solo."},
 {date:"Mar 15 2026",ref:"Salmos 56:3",text:"En el día que temo, yo en ti confío.",reflection:"La confianza en Dios es paz en medio del ruido."}
];
const today=verses[Math.floor(Date.now()/86400000)%verses.length]; function fillToday(v){$("verseText").textContent='“'+v.text+'”';$("verseRef").textContent=v.ref;$("reflection").textContent=v.reflection} fillToday(today);
const verseList=$("verseList"), verseDetail=$("verseDetail"); function showVerse(i){const v=verses[i]; verseDetail.innerHTML=`<h3>${v.date}</h3><blockquote>“${v.text}”</blockquote><p class="verse-ref">${v.ref}</p><p class="reflection">${v.reflection}</p>`} verses.forEach((v,i)=>{const b=document.createElement("button");b.className="verse-item";b.innerHTML=`${v.date}<span>${v.ref}</span>`;b.onclick=()=>showVerse(i);verseList.appendChild(b)}); showVerse(0);
function go(page){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$("page-"+page)?.classList.add("active");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===page));menu.classList.remove("open");overlay.classList.remove("show");window.scrollTo({top:0,behavior:"smooth"})} document.querySelectorAll("[data-page]").forEach(el=>el.addEventListener("click",()=>go(el.dataset.page)));
$("openMenu").onclick=()=>{menu.classList.add("open");overlay.classList.add("show")}; $("closeMenu").onclick=overlay.onclick=()=>{menu.classList.remove("open");overlay.classList.remove("show")};
async function shareApp(){const shareData={title:"Edén La Radio",text:t.tagline+". Música cristiana 24/7.",url:location.href}; if(navigator.share){await navigator.share(shareData)}else{await navigator.clipboard.writeText(location.href);alert(lang==="es"?"Link copiado":"Link copied")}} $("shareBtn").onclick=shareApp; $("shareBtn2").onclick=shareApp;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false}); $("installBtn").addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").hidden=true}); if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"))}
